# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ksail < Formula
  desc "Cli tool for provisioning gitops enabled k8s clusters in docker"
  homepage "https://github.com/devantler/ksail"
  url "https://github.com/devantler/ksail/archive/refs/tags/v1.0.8.tar.gz"
  sha256 "e4f30bfebe88bfa118928c4e7ab1e2219f3ade47c42b7c7131a0856da534a0e6"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "ksail"
  end
end
